# Generated by Django 4.2.24 on 2025-09-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviemate', '0002_streamplatform_watchlist_delete_moviedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchplatform', to='moviemate.streamplatform'),
            preserve_default=False,
        ),
    ]
